wip: tx spec
wevm/frog-archived pull request #10
Opened 2024-02-27 23:36 UTC by jxom

2024-02-28 19:55 UTC, gakonst commented
ref https://www.notion.so/warpcast/Frames-Transactions-Public-Draft-c2e0d3210d684b4cb7803de1810db36d?pvs=4#96d3bcdae85040e69967de9696cd3eaf

2024-02-28 19:57 UTC, gakonst commented on playground/src/index.tsx
> +export const erc20Abi = [
we should viemify these, human readable abi etc.

2024-02-28 19:57 UTC, gakonst commented on src/components/Button.tsx
> +  ] as unknown as HtmlEscapedString
clean

2024-02-28 19:57 UTC, gakonst commented on src/types/utils.ts
> +export type Widen<type> =
magic

2024-02-29 14:34 UTC, dalechyn requested changes
Typings question.

2024-02-29 14:34 UTC, dalechyn commented on playground/src/index.tsx
> +    chainId: '10',
Shouldn't `value` be a `bigint` and `chainId` a `number`?

2024-03-03 18:53 UTC, tmm commented on src/components/Button.tsx
> +  location: string
Does it make sense to use `target` instead to keep inline with the spec?

2024-03-03 21:45 UTC, closed without merging

2024-03-03 21:45 UTC, jxom commented
Succeeded by #63.