refactor: split icons to packages
wevm/frog-archived pull request #255
Opened 2024-04-14 12:13 UTC by dalechyn

Should fix #240.

2024-04-14 12:14 UTC, dalechyn commented on src/package.json
> +  "authors": ["awkweb.eth", "jxom.eth"],
```suggestion
  "authors": [
    "awkweb.eth",
    "jxom.eth"
  ],
```

2024-05-15 23:19 UTC, tmm requested changes

2024-05-15 23:19 UTC, tmm commented on src/ui/Icon.tsx
> +   * @default lucide from 'frog/ui/lucide'
```suggestion
   * @default lucide (from 'frog/ui/icons')
```

2024-05-15 23:19 UTC, tmm commented on src/package.json
Can we add a `'frog/ui/icons'` entrypoint that exports all the icon sets for folks that aren't in a constrained environment? Makes it easier to swap collections and try things out (also looks nicer).

```ts
import { lucide, heroicons } from 'frog/ui/icons'
```

2024-05-15 23:19 UTC, tmm commented on site/pages/ui/ui-system.mdx
> +import { lucide } from 'frog/ui/icons/lucide'
```suggestion
import { lucide } from 'frog/ui/icons'
```

2024-05-15 23:19 UTC, tmm commented on site/pages/ui/createSystem.mdx
> +import { lucide } from 'frog/ui/icons/lucide' // [!code focus]
```suggestion
import { lucide } from 'frog/ui/icons' // [!code focus]
```

2024-05-15 23:19 UTC, tmm commented on site/pages/ui/createSystem.mdx
> +- **Default:** `frog/ui/icons/lucide`
```suggestion
- **Default:** lucide
```

2024-05-15 23:19 UTC, tmm commented on site/pages/ui/Icon.mdx
> +import { heroicons } from 'frog/ui/icons/heroicons' // [!code focus]
```suggestion
import { heroicons } from 'frog/ui/icons' // [!code focus]
```

2024-05-15 23:19 UTC, tmm commented on site/pages/ui/Icon.mdx
> +Icon collection to use for resolving icons. Defaults to `lucide` imported from `'frog/ui/icons/lucide'`.
```suggestion
Icon collection to use for resolving icons. Defaults to `lucide` imported from `'frog/ui/icons'`.
```

2024-05-15 23:19 UTC, tmm commented on playground/src/ui-system.tsx
> +import { heroicons } from '../../src/_lib/ui/icons/heroicons/index.js'
```suggestion
import { heroicons, lucide, radixIcons } from 'frog/ui/icons'
```

2024-05-15 23:19 UTC, tmm commented on .changeset/many-schools-reflect.md
> +- `frog/ui/icons/radix-icons`
```suggestion
**Breaking change** Frog UI `icon` property requires an icon map imported from the `'frog/ui/icons'` entrypoint. This also makes it easier for you to supply your own custom icons.

\```diff
+ import { lucide } from 'frog/ui/icons'

export const system = createSystem({
- icons: 'lucide',
+ icons: lucide,
})
\```

In addition, the following separate entrypoints were added for resource constrained environments.

- `frog/ui/icons/heroicons`
- `frog/ui/icons/lucide`
- `frog/ui/icons/radix-icons`
```

2024-05-16 11:06 UTC, dalechyn commented on src/package.json
a47a79a

2024-05-16 13:39 UTC, tmm approved these changes

2024-05-16 13:39 UTC, merged